// CHW (Community Health Worker) Dashboard Dummy Data
// This file contains realistic dummy data for testing and development

import { 
  CHWStats, 
  CHWPatient, 
  HealthScreening, 
  HealthEducationSession, 
  CommunityOutreachEvent, 
  HealthReferral, 
  HealthResource 
} from '../dashboards/chw/index';

// CHW Statistics
export const dummyCHWStats: CHWStats = {
  totalPatients: 156,
  activePatients: 89,
  completedScreenings: 234,
  pendingReferrals: 12,
  educationSessions: 18,
  communityEvents: 6,
  averageFollowUpTime: 24,
  patientSatisfactionRate: 94.2,
};

// CHW Patients
export const dummyCHWPatients: CHWPatient[] = [
  {
    id: 'chw-patient-1',
    name: 'Maria Rodriguez',
    age: 45,
    gender: 'Female',
    phone: '+1-555-0101',
    email: 'maria.rodriguez@email.com',
    address: '123 Oak Street, Brooklyn, NY 11201',
    emergencyContact: {
      name: 'Carlos Rodriguez',
      phone: '+1-555-0102',
      relationship: 'Husband',
    },
    healthConditions: ['Type 2 Diabetes', 'Hypertension'],
    riskFactors: ['Family history of diabetes', 'Sedentary lifestyle'],
    lastVisit: '2024-12-08T10:30:00Z',
    nextAppointment: '2024-12-15T14:00:00Z',
    status: 'active',
    priority: 'high',
    insuranceStatus: 'medicaid',
    preferredLanguage: 'Spanish',
    culturalConsiderations: ['Prefers female providers', 'Traditional remedies important'],
    socialDeterminants: {
      housing: 'stable',
      food: 'insecure',
      transportation: 'limited',
      employment: 'underemployed',
      education: 'High School',
    },
    caseId: 'CHW-2024-001',
    assignedCHW: 'chw-worker-1',
    notes: 'Patient is motivated to manage diabetes but needs support with nutrition and medication adherence.',
  },
  {
    id: 'chw-patient-2',
    name: 'James Thompson',
    age: 62,
    gender: 'Male',
    phone: '+1-555-0103',
    address: '456 Pine Avenue, Queens, NY 11375',
    emergencyContact: {
      name: 'Sarah Thompson',
      phone: '+1-555-0104',
      relationship: 'Wife',
    },
    healthConditions: ['COPD', 'Depression'],
    riskFactors: ['Former smoker', 'Social isolation'],
    lastVisit: '2024-12-05T09:15:00Z',
    nextAppointment: '2024-12-20T11:00:00Z',
    status: 'active',
    priority: 'medium',
    insuranceStatus: 'medicare',
    preferredLanguage: 'English',
    socialDeterminants: {
      housing: 'stable',
      food: 'secure',
      transportation: 'available',
      employment: 'unemployed',
      education: 'College',
    },
    caseId: 'CHW-2024-002',
    assignedCHW: 'chw-worker-1',
    notes: 'Patient struggles with medication compliance and social isolation since retirement.',
  },
  {
    id: 'chw-patient-3',
    name: 'Aisha Patel',
    age: 28,
    gender: 'Female',
    phone: '+1-555-0105',
    email: 'aisha.patel@email.com',
    address: '789 Elm Street, Manhattan, NY 10003',
    emergencyContact: {
      name: 'Raj Patel',
      phone: '+1-555-0106',
      relationship: 'Brother',
    },
    healthConditions: ['Gestational Diabetes'],
    riskFactors: ['First pregnancy', 'Family history of diabetes'],
    lastVisit: '2024-12-10T13:45:00Z',
    nextAppointment: '2024-12-17T10:30:00Z',
    status: 'active',
    priority: 'high',
    insuranceStatus: 'insured',
    preferredLanguage: 'English',
    culturalConsiderations: ['Vegetarian diet', 'Religious considerations for appointments'],
    socialDeterminants: {
      housing: 'stable',
      food: 'secure',
      transportation: 'available',
      employment: 'employed',
      education: 'Graduate Degree',
    },
    caseId: 'CHW-2024-003',
    assignedCHW: 'chw-worker-1',
    notes: 'Pregnant patient needs close monitoring for gestational diabetes management.',
  },
];

// Health Screenings
export const dummyHealthScreenings: HealthScreening[] = [
  {
    id: 'screening-1',
    patientId: 'chw-patient-1',
    patientName: 'Maria Rodriguez',
    screeningType: 'blood_pressure',
    status: 'completed',
    scheduledDate: '2024-12-08T10:30:00Z',
    completedDate: '2024-12-08T10:45:00Z',
    results: {
      values: {
        systolic: 145,
        diastolic: 92,
        pulse: 78,
      },
      interpretation: 'abnormal',
      recommendations: [
        'Continue current medication',
        'Reduce sodium intake',
        'Follow up in 2 weeks',
      ],
    },
    followUpRequired: true,
    followUpDate: '2024-12-22T10:30:00Z',
    referralNeeded: false,
    caseId: 'CHW-2024-001',
  },
  {
    id: 'screening-2',
    patientId: 'chw-patient-1',
    patientName: 'Maria Rodriguez',
    screeningType: 'diabetes',
    status: 'scheduled',
    scheduledDate: '2024-12-15T14:00:00Z',
    followUpRequired: false,
    referralNeeded: false,
    caseId: 'CHW-2024-001',
  },
  {
    id: 'screening-3',
    patientId: 'chw-patient-2',
    patientName: 'James Thompson',
    screeningType: 'depression',
    status: 'completed',
    scheduledDate: '2024-12-05T09:15:00Z',
    completedDate: '2024-12-05T09:30:00Z',
    results: {
      values: {
        phq9_score: 12,
      },
      interpretation: 'borderline',
      recommendations: [
        'Consider counseling referral',
        'Increase social activities',
        'Monitor mood changes',
      ],
    },
    followUpRequired: true,
    followUpDate: '2024-12-19T09:15:00Z',
    referralNeeded: true,
    referralProvider: 'Community Mental Health Center',
    caseId: 'CHW-2024-002',
  },
];

// Health Education Sessions
export const dummyHealthEducationSessions: HealthEducationSession[] = [
  {
    id: 'education-1',
    title: 'Diabetes Management Workshop',
    topic: 'diabetes_management',
    type: 'group',
    description: 'Learn practical strategies for managing Type 2 diabetes through diet, exercise, and medication adherence.',
    targetAudience: ['Adults with diabetes', 'Family caregivers'],
    scheduledDate: '2024-12-18T14:00:00Z',
    duration: 90,
    location: 'Community Health Center - Room A',
    facilitator: 'Dr. Sarah Johnson, CHW',
    maxParticipants: 15,
    registeredParticipants: 12,
    status: 'planned',
    materials: ['Blood glucose monitors', 'Educational handouts', 'Healthy snack samples'],
    objectives: [
      'Understand blood sugar monitoring',
      'Learn meal planning strategies',
      'Practice medication management',
      'Identify warning signs of complications',
    ],
  },
  {
    id: 'education-2',
    title: 'Heart-Healthy Cooking Class',
    topic: 'nutrition',
    type: 'workshop',
    description: 'Hands-on cooking class focusing on heart-healthy recipes and nutrition education.',
    targetAudience: ['Adults with hypertension', 'Community members'],
    scheduledDate: '2024-12-20T16:00:00Z',
    duration: 120,
    location: 'Community Kitchen',
    facilitator: 'Maria Santos, Nutritionist',
    maxParticipants: 10,
    registeredParticipants: 8,
    status: 'planned',
    materials: ['Cooking ingredients', 'Recipe cards', 'Nutrition guides'],
    objectives: [
      'Learn low-sodium cooking techniques',
      'Understand portion control',
      'Practice meal preparation',
    ],
  },
  {
    id: 'education-3',
    title: 'Mental Health First Aid',
    topic: 'mental_health',
    type: 'community_event',
    description: 'Community workshop on recognizing and responding to mental health crises.',
    targetAudience: ['Community members', 'Family caregivers', 'Community leaders'],
    scheduledDate: '2024-12-12T18:00:00Z',
    duration: 180,
    location: 'Community Center Main Hall',
    facilitator: 'Dr. Michael Chen, LCSW',
    registeredParticipants: 25,
    attendedParticipants: 23,
    status: 'completed',
    materials: ['Resource directories', 'Crisis hotline cards', 'Educational brochures'],
    objectives: [
      'Recognize signs of mental health crisis',
      'Learn de-escalation techniques',
      'Understand available resources',
    ],
    feedback: {
      rating: 4.7,
      comments: [
        'Very informative and practical',
        'Great resources provided',
        'Would like more advanced training',
      ],
    },
  },
];

// Community Outreach Events
export const dummyCommunityOutreachEvents: CommunityOutreachEvent[] = [
  {
    id: 'outreach-1',
    name: 'Community Health Fair',
    type: 'health_fair',
    description: 'Free health screenings, vaccinations, and health education for the community.',
    date: '2024-12-21',
    startTime: '09:00',
    endTime: '15:00',
    location: 'Central Park Community Center',
    targetPopulation: ['Uninsured adults', 'Elderly residents', 'Families with children'],
    expectedAttendance: 200,
    services: [
      'Blood pressure screening',
      'Diabetes screening',
      'Flu vaccinations',
      'Health education',
      'Resource referrals',
    ],
    partners: ['Local Hospital', 'Pharmacy Chain', 'Health Department'],
    coordinator: 'Lisa Martinez, CHW Supervisor',
    volunteers: ['CHW Team', 'Nursing students', 'Community volunteers'],
    status: 'planning',
    budget: 5000,
  },
  {
    id: 'outreach-2',
    name: 'Senior Wellness Check',
    type: 'screening_event',
    description: 'Door-to-door wellness checks for homebound seniors in the community.',
    date: '2024-12-14',
    startTime: '10:00',
    endTime: '16:00',
    location: 'Seniors Housing Complex',
    targetPopulation: ['Homebound seniors', 'Isolated elderly'],
    expectedAttendance: 50,
    actualAttendance: 47,
    services: [
      'Wellness assessments',
      'Medication reviews',
      'Social support connections',
      'Emergency contact updates',
    ],
    partners: ['Senior Services', 'Meals on Wheels'],
    coordinator: 'Robert Kim, CHW',
    volunteers: ['CHW Team', 'Social work students'],
    status: 'completed',
    outcomes: {
      screeningsCompleted: 47,
      referralsMade: 8,
      educationMaterialsDistributed: 47,
      newPatientRegistrations: 3,
    },
    feedback: {
      rating: 4.9,
      comments: [
        'Much needed service',
        'Very caring staff',
        'Helped connect to resources',
      ],
    },
  },
];

// Health Referrals
export const dummyHealthReferrals: HealthReferral[] = [
  {
    id: 'referral-1',
    patientId: 'chw-patient-2',
    patientName: 'James Thompson',
    referralType: 'mental_health',
    provider: 'Community Mental Health Center',
    providerContact: '+1-555-0200',
    reason: 'Depression screening indicates need for professional counseling and possible medication evaluation.',
    urgency: 'routine',
    referralDate: '2024-12-05',
    appointmentDate: '2024-12-19T10:00:00Z',
    status: 'scheduled',
    caseId: 'CHW-2024-002',
  },
  {
    id: 'referral-2',
    patientId: 'chw-patient-1',
    patientName: 'Maria Rodriguez',
    referralType: 'specialist',
    provider: 'Endocrinology Associates',
    providerContact: '+1-555-0201',
    reason: 'Uncontrolled diabetes requiring specialist evaluation and medication adjustment.',
    urgency: 'urgent',
    referralDate: '2024-12-08',
    status: 'pending',
    followUpDate: '2024-12-15',
    barriers: ['Insurance authorization needed', 'Transportation challenges'],
    notes: 'Patient needs help with insurance paperwork and transportation to appointment.',
    caseId: 'CHW-2024-001',
  },
  {
    id: 'referral-3',
    patientId: 'chw-patient-3',
    patientName: 'Aisha Patel',
    referralType: 'specialist',
    provider: 'Maternal-Fetal Medicine Clinic',
    providerContact: '+1-555-0202',
    reason: 'High-risk pregnancy due to gestational diabetes requiring specialist monitoring.',
    urgency: 'urgent',
    referralDate: '2024-12-10',
    appointmentDate: '2024-12-16T14:30:00Z',
    status: 'scheduled',
    outcome: 'Appointment scheduled successfully. Patient educated on importance of specialist care.',
    caseId: 'CHW-2024-003',
  },
];

// Health Resources
export const dummyHealthResources: HealthResource[] = [
  {
    id: 'resource-1',
    name: 'Community Health Center',
    category: 'healthcare_provider',
    description: 'Comprehensive primary care services including family medicine, pediatrics, and preventive care.',
    address: '123 Health Street, Brooklyn, NY 11201',
    phone: '+1-555-0300',
    email: 'info@communityhealthcenter.org',
    website: 'https://communityhealthcenter.org',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM, Sat 9:00 AM - 2:00 PM',
    services: [
      'Primary care',
      'Preventive screenings',
      'Chronic disease management',
      'Immunizations',
      'Health education',
    ],
    eligibility: ['All ages welcome', 'Sliding fee scale available', 'Insurance accepted'],
    languages: ['English', 'Spanish', 'Arabic'],
    accessibility: ['Wheelchair accessible', 'Sign language interpreter available'],
    cost: 'sliding_scale',
    waitTime: '1-2 weeks for routine appointments',
    lastUpdated: '2024-12-01',
    isActive: true,
    contactPerson: 'Dr. Maria Santos',
    rating: 4.5,
    reviews: ['Excellent care', 'Bilingual staff helpful', 'Clean facilities'],
  },
  {
    id: 'resource-2',
    name: 'Neighborhood Pharmacy',
    category: 'pharmacy',
    description: 'Full-service pharmacy with medication counseling and health screenings.',
    address: '456 Main Street, Queens, NY 11375',
    phone: '+1-555-0301',
    website: 'https://neighborhoodpharmacy.com',
    hours: 'Mon-Sat 9:00 AM - 8:00 PM, Sun 10:00 AM - 6:00 PM',
    services: [
      'Prescription medications',
      'Over-the-counter products',
      'Medication counseling',
      'Blood pressure checks',
      'Flu shots',
    ],
    eligibility: ['Open to public', 'Insurance accepted'],
    languages: ['English', 'Spanish'],
    accessibility: ['Wheelchair accessible'],
    cost: 'insurance_accepted',
    waitTime: 'Usually same day',
    lastUpdated: '2024-11-28',
    isActive: true,
    contactPerson: 'PharmD John Lee',
    rating: 4.2,
  },
  {
    id: 'resource-3',
    name: 'Food Pantry Network',
    category: 'food_assistance',
    description: 'Emergency food assistance and nutrition education programs for families in need.',
    address: '789 Community Avenue, Manhattan, NY 10003',
    phone: '+1-555-0302',
    email: 'help@foodpantrynetwork.org',
    hours: 'Tue, Thu, Sat 10:00 AM - 2:00 PM',
    services: [
      'Emergency food boxes',
      'Fresh produce distribution',
      'Nutrition counseling',
      'SNAP application assistance',
    ],
    eligibility: ['Income verification required', 'Residency in service area'],
    languages: ['English', 'Spanish', 'French'],
    accessibility: ['Wheelchair accessible', 'Home delivery for seniors'],
    cost: 'free',
    waitTime: 'Walk-in basis',
    lastUpdated: '2024-12-05',
    isActive: true,
    contactPerson: 'Sarah Williams',
    rating: 4.8,
    notes: 'Especially busy during holiday seasons. Call ahead to confirm availability.',
  },
];

// Export all dummy data
export const CHWDummyData = {
  stats: dummyCHWStats,
  patients: dummyCHWPatients,
  screenings: dummyHealthScreenings,
  educationSessions: dummyHealthEducationSessions,
  outreachEvents: dummyCommunityOutreachEvents,
  referrals: dummyHealthReferrals,
  resources: dummyHealthResources,
};

export default CHWDummyData;