/**
 * Storage Constants
 * Centralized storage keys for AsyncStorage
 * Prevents key collision and provides type-safe access
 */

export const STORAGE_KEYS = {
  // Query cache
  QUERY_CACHE: 'KINTARAA_QUERY_CACHE',

  // Sync queue
  SYNC_QUEUE: 'KINTARAA_SYNC_QUEUE',

  // Network state
  NETWORK_STATE: 'KINTARAA_NETWORK_STATE',
  LAST_SYNC_TIME: 'KINTARAA_LAST_SYNC',

  // Encryption
  ENCRYPTION_KEY: 'KINTARAA_ENCRYPTION_KEY',

  // User data (encrypted)
  USER_PROFILE: 'KINTARAA_USER_PROFILE',

  // Incidents (encrypted)
  INCIDENTS: 'KINTARAA_INCIDENTS',
  INCIDENT_DRAFTS: 'KINTARAA_INCIDENT_DRAFTS',

  // Safety plans (encrypted)
  SAFETY_PLANS: 'KINTARAA_SAFETY_PLANS',
  EMERGENCY_CONTACTS: 'KINTARAA_EMERGENCY_CONTACTS',

  // Evidence files (encrypted)
  EVIDENCE_FILES: 'KINTARAA_EVIDENCE_FILES',

  // Messages (encrypted)
  MESSAGES: 'KINTARAA_MESSAGES',
  CONVERSATIONS: 'KINTARAA_CONVERSATIONS',

  // Wellbeing data
  WELLBEING_LOGS: 'KINTARAA_WELLBEING_LOGS',

  // Provider data
  ASSIGNMENTS: 'KINTARAA_ASSIGNMENTS',
  NOTIFICATIONS: 'KINTARAA_NOTIFICATIONS',
} as const;

// Sensitive keys that should be encrypted
export const SENSITIVE_STORAGE_KEYS = [
  STORAGE_KEYS.USER_PROFILE,
  STORAGE_KEYS.INCIDENTS,
  STORAGE_KEYS.INCIDENT_DRAFTS,
  STORAGE_KEYS.SAFETY_PLANS,
  STORAGE_KEYS.EMERGENCY_CONTACTS,
  STORAGE_KEYS.EVIDENCE_FILES,
  STORAGE_KEYS.MESSAGES,
  STORAGE_KEYS.CONVERSATIONS,
] as const;

// Keys to clear on logout
export const CLEAR_ON_LOGOUT_KEYS = [
  STORAGE_KEYS.INCIDENTS,
  STORAGE_KEYS.INCIDENT_DRAFTS,
  STORAGE_KEYS.SAFETY_PLANS,
  STORAGE_KEYS.EMERGENCY_CONTACTS,
  STORAGE_KEYS.EVIDENCE_FILES,
  STORAGE_KEYS.MESSAGES,
  STORAGE_KEYS.CONVERSATIONS,
  STORAGE_KEYS.SYNC_QUEUE,
  STORAGE_KEYS.LAST_SYNC_TIME,
] as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
